# Generated by Django 4.2.2 on 2023-07-03 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_vote',
            old_name='post',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='comment_vote',
            unique_together={('user', 'comment')},
        ),
    ]
