# Generated by Django 4.2.2 on 2023-07-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_post_comment_vote_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_vote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
    ]
