# Generated by Django 4.2.2 on 2023-06-27 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 6, 27, 13, 3, 40, 706143)),
        ),
    ]
