# Generated by Django 4.2.2 on 2023-06-26 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2023, 6, 26, 15, 30, 25, 476348)),
        ),
        migrations.AlterUniqueTogether(
            name='useringroup',
            unique_together={('user_id', 'group_id')},
        ),
    ]
