# Generated by Django 4.2.2 on 2023-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset',
            field=models.BooleanField(default=False),
        ),
    ]
